# Generated by Django 4.2 on 2024-07-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MultiImg", "0002_faceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="MultiImg.person",
            ),
        ),
    ]
