# Generated by Django 4.2.13 on 2024-07-17 01:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0003_alter_image_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='face_encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
