# Generated by Django 4.2.13 on 2024-07-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0004_image_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='face_encoding',
        ),
    ]
