# Generated by Django 4.2.13 on 2024-07-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0005_remove_image_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
