# Generated by Django 4.2.13 on 2024-07-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0006_image_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
