# Generated by Django 4.2.13 on 2024-07-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0007_faceimage_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='person',
        ),
    ]
