# Generated by Django 4.2.13 on 2024-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0008_remove_image_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
