# Generated by Django 4.2.13 on 2024-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiImg', '0009_alter_image_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
