# Generated by Django 4.2.13 on 2024-07-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commercial_categ_image', models.ImageField(upload_to='commercial_category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider_images')),
            ],
        ),
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='commercial_images')),
                ('com_categ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.commercial_category')),
            ],
        ),
    ]
