# Generated by Django 4.2.13 on 2024-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_image', models.ImageField(upload_to='commercial_images')),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_description', models.TextField(null=True)),
            ],
        ),
    ]
