# Generated by Django 4.2.13 on 2024-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial_category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
