# Generated by Django 4.2.13 on 2024-08-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_commercial_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercials',
            name='com_categ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_images', to='photography.commercial_category'),
        ),
    ]
